local docs = {
  autotrim = 'AutoTrim, On|Off',
  blockinput = 'BlockInput, Mode',
  click = 'Click',
  clipwait = 'ClipWait [, SecondsToWait, 1]',
  control = 'Control, Cmd [, Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlclick = 'ControlClick [, Control-or-Pos, WinTitle, WinText, WhichButton, ClickCount, Options, ExcludeTitle, ExcludeText]',
  controlfocus = 'ControlFocus [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlget = 'ControlGet, OutputVar, Cmd [, Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlgetfocus = 'ControlGetFocus, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlgetpos = 'ControlGetPos [, X, Y, Width, Height, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlgettext = 'ControlGetText, OutputVar [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlmove = 'ControlMove, Control, X, Y, Width, Height [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlsend = 'ControlSend [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlsendraw = 'ControlSendRaw [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  controlsettext = 'ControlSetText [, Control, NewText, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  coordmode = 'CoordMode, ToolTip|Pixel|Mouse|Caret|Menu [, Screen|Window|Client]',
  critical = 'Critical 50 [, Off]',
  detecthiddentext = 'DetectHiddenText, On|Off',
  detecthiddenwindows = 'DetectHiddenWindows, On|Off',
  drive = 'Drive, Sub-command [, Drive, Value]',
  driveget = 'DriveGet, OutputVar, Cmd [, Value]',
  drivespacefree = 'DriveSpaceFree, OutputVar, Path',
  edit = 'Edit',
  EnvAdd = 'EnvAdd, Var, Value [, TimeUnits]',
  envdiv = 'EnvDiv, Var, Value',
  envget = 'EnvGet, OutputVar, EnvVarName',
  envmult = 'EnvMult, Var, Value',
  envset = 'EnvSet, EnvVar, Value',
  envsub = 'EnvSub, Var, Value [, TimeUnits]',
  envupdate = 'EnvUpdate',
  exit = 'Exit [, ExitCode]',
  exitapp = 'ExitApp [, ExitCode]',
  fileappend = 'FileAppend [, Text, Filename, Encoding]',
  filecopy = 'FileCopy, SourcePattern, DestPattern [, Flag]',
  filecopydir = 'FileCopyDir, Source, Dest [, Flag]',
  filecreatedir = 'FileCreateDir, DirName',
  filecreateshortcut = 'FileCreateShortcut, Target, LinkFile [, WorkingDir, Args, Description, IconFile, ShortcutKey, IconNumber, RunState]',
  filedelete = 'FileDelete, FilePattern',
  fileencoding = 'FileEncoding [, Encoding]',
  filegetattrib = 'FileGetAttrib, OutputVar [, Filename]',
  filegetshortcut = 'FileGetShortcut, LinkFile [, OutTarget, OutDir, OutArgs, OutDescription, OutIcon, OutIconNum, OutRunState]',
  filegetsize = 'FileGetSize, OutputVar [, Filename, Units]',
  filegettime = 'FileGetTime, OutputVar [, Filename, WhichTime]',
  filegetversion = 'FileGetVersion, OutputVar [, Filename]',
  fileinstall = 'FileInstall, Source, Dest [, Flag]',
  filemove = 'FileMove, SourcePattern, DestPattern [, Flag]',
  filemovedir = 'FileMoveDir, Source, Dest [, Flag]',
  fileread = 'FileRead, OutputVar, Filename',
  filereadline = 'FileReadLine, OutputVar, Filename, LineNum',
  filerecycle = 'FileRecycle, FilePattern',
  filerecycleempty = 'FileRecycleEmpty [, DriveLetter]',
  fileremovedir = 'FileRemoveDir, DirName [, Recurse?]',
  fileselectfile = 'FileSelectFile, OutputVar [, Options, RootDirFilename, Prompt, Filter]',
  fileselectfolder = 'FileSelectFolder, OutputVar [, StartingFolder, Options, Prompt]',
  filesetattrib = 'FileSetAttrib, Attributes [, FilePattern, OperateOnFolders?, Recurse?]',
  filesettime = 'FileSetTime [, YYYYMMDDHH24MISS, FilePattern, WhichTime, OperateOnFolders?, Recurse?]',
  formattime = 'FormatTime, OutputVar [, YYYYMMDDHH24MISS, Format]',
  getkeystate = 'GetKeyState, OutputVar, KeyName [, Mode]',
  groupactivate = 'GroupActivate, GroupName [, R]',
  groupadd = 'GroupAdd, GroupName [, WinTitle, WinText, Label, ExcludeTitle, ExcludeText]',
  groupclose = 'GroupClose, GroupName [, A|R]',
  groupdeactivate = 'GroupDeactivate, GroupName [, R]',
  gui = 'Gui, sub-command [, Param2, Param3, Param4]',
  guicontrol = 'GuiControl, Sub-command, ControlID [, Param3]',
  guicontrolget = 'GuiControlGet, OutputVar [, Sub-command, ControlID, Param4]',
  hotkey = { 'Hotkey, If [, Expression]',
             'Hotkey, If, % FunctionObject',
             'Hotkey, IfWinActive/Exist [, WinTitle, WinText]',
             'Hotkey, KeyName [, Label, Options]', },
  imagesearch = 'ImageSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ImageFile',
  inidelete = 'IniDelete, Filename, Section [, Key]',
  iniread = { 'IniRead, OutputVar, Filename, Section, Key [, Default]',
              'IniRead, OutputVarSection, Filename, Section',
              'IniRead, OutputVarSectionNames, Filename', },
  iniwrite = { 'IniWrite, Pairs, Filename, Section',
               'IniWrite, Value, Filename, Section, Key', },
  input = 'Input [, OutputVar, Options, EndKeys, MatchList]',
  inputbox = 'InputBox, OutputVar [, Title, Prompt, HIDE, Width, Height, X, Y, Font, Timeout, Default]',
  keyhistory = 'KeyHistory',
  keywait = 'KeyWait, KeyName [, Options]',
  listhotkeys = 'ListHotkeys',
  listlines = 'ListLines [, On|Off]',
  listvars = 'ListVars',
  menu = 'Menu, MenuName, Cmd [, P3, P4, P5]',
  mouseclick = 'MouseClick [, WhichButton, X, Y, ClickCount, Speed, D|U, R]',
  mouseclickdrag = 'MouseClickDrag, WhichButton, X1, Y1, X2, Y2 [, Speed, R]',
  mousegetpos = 'MouseGetPos [, OutputVarX, OutputVarY, OutputVarWin, OutputVarControl, 1|2|3]',
  mousemove = 'MouseMove, X, Y [, Speed, R]',
  msgbox = { 'MsgBox [, Options, Title, Text, Timeout]',
             'MsgBox, Text', },
  onexit = 'OnExit [, Label]',
  outputdebug = 'OutputDebug, Text',
  pause = 'Pause [, On|Off|Toggle, OperateOnUnderlyingThread?]',
  pixelgetcolor = 'PixelGetColor, OutputVar, X, Y [, Alt|Slow|RGB]',
  pixelsearch = 'PixelSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ColorID [, Variation, Fast|RGB]',
  postmessage = 'PostMessage, Msg [, wParam, lParam, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  process = 'Process, Cmd [, PID-or-Name, Param3]',
  progress = { 'Progress, Off',
               'Progress, ProgressParam1 [, SubText, MainText, WinTitle, FontName]', },
  random = { 'Random, , NewSeed',
             'Random, OutputVar [, Min, Max]', },
  regdelete = { 'RegDelete, KeyName [, ValueName]',
                'RegDelete, RootKey, SubKey [, ValueName]', },
  regread = { 'RegRead, OutputVar, KeyName [, ValueName]',
              'RegRead, OutputVar, RootKey, SubKey [, ValueName]', },
  regwrite = { 'RegWrite, ValueType, KeyName [, ValueName, Value]',
               'RegWrite, ValueType, RootKey, SubKey [, ValueName, Value]', },
  reload = 'Reload',
  run = 'Run, Target [, WorkingDir, Max|Min|Hide|UseErrorLevel, OutputVarPID]',
  runas = 'RunAs [, User, Password, Domain]',
  runwait = 'RunWait, Target [, WorkingDir, Max|Min|Hide|UseErrorLevel, OutputVarPID]',
  send = 'Send Keys',
  sendevent = 'SendEvent Keys',
  sendinput = 'SendInput Keys',
  sendlevel = 'SendLevel, Level',
  sendmessage = 'SendMessage, Msg [, wParam, lParam, Control, WinTitle, WinText, ExcludeTitle, ExcludeText, Timeout]',
  sendmode = 'SendMode Input|Play|Event|InputThenPlay',
  sendplay = 'SendPlay Keys',
  sendraw = 'SendRaw Keys',
  setbatchlines = { 'SetBatchLines, 20ms',
                    'SetBatchLines, LineCount', },
  setcapslockstate = 'SetCapsLockState [, State]',
  setcontroldelay = 'SetControlDelay, Delay',
  setdefaultmousespeed = 'SetDefaultMouseSpeed, Speed',
  setenv = 'SetEnv, Var, Value',
  setformat = 'SetFormat, NumberType, Format',
  setkeydelay = 'SetKeyDelay [, Delay, PressDuration, Play]',
  setmousedelay = 'SetMouseDelay, Delay [, Play]',
  setnumlockstate = 'SetNumLockState [, State]',
  setregview = 'SetRegView, RegView',
  setscrolllockstate = 'SetScrollLockState [, State]',
  setstorecapslockmode = 'SetStoreCapsLockMode, On|Off',
  settimer = 'SetTimer [, Label, Period|On|Off|Delete, Priority]',
  settitlematchmode = { 'SetTitleMatchMode, Fast|Slow',
                        'SetTitleMatchMode, MatchMode', },
  setwindelay = 'SetWinDelay, Delay',
  setworkingdir = 'SetWorkingDir, DirName',
  shutdown = 'Shutdown, Code',
  sleep = 'Sleep, DelayInMilliseconds',
  sort = 'Sort, VarName [, Options]',
  soundbeep = 'SoundBeep [, Frequency, Duration]',
  soundget = 'SoundGet, OutputVar [, ComponentType, ControlType, DeviceNumber]',
  soundgetwavevolume = 'SoundGetWaveVolume, OutputVar [, DeviceNumber]',
  soundplay = 'SoundPlay, Filename [, wait]',
  soundset = 'SoundSet, NewSetting [, ComponentType, ControlType, DeviceNumber]',
  soundsetwavevolume = 'SoundSetWaveVolume, Percent [, DeviceNumber]',
  splashimage = { 'SplashImage [, ImageFile, Options, SubText, MainText, WinTitle, FontName]',
                  'SplashImage, Off', },
  splashtextoff = 'SplashTextOff',
  splashtexton = 'SplashTextOn [, Width, Height, Title, Text]',
  splitpath = 'SplitPath, InputVar [, OutFileName, OutDir, OutExtension, OutNameNoExt, OutDrive]',
  statusbargettext = 'StatusBarGetText, OutputVar [, Part#, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  statusbarwait = 'StatusBarWait [, BarText, Seconds, Part#, WinTitle, WinText, Interval, ExcludeTitle, ExcludeText]',
  stringcasesense = 'StringCaseSense, On|Off|Locale',
  stringgetpos = 'StringGetPos, OutputVar, InputVar, SearchText [, L#|R#, Offset]',
  stringleft = 'StringLeft, OutputVar, InputVar, Count',
  stringlen = 'StringLen, OutputVar, InputVar',
  stringlower = 'StringLower, OutputVar, InputVar [, T]',
  stringmid = 'StringMid, OutputVar, InputVar, StartChar [, Count, L]',
  stringreplace = 'StringReplace, OutputVar, InputVar, SearchText [, ReplaceText, ReplaceAll?]',
  stringright = 'StringRight, OutputVar, InputVar, Count',
  stringsplit = 'StringSplit, OutputArray, InputVar [, Delimiters, OmitChars]',
  stringtrimleft = 'StringTrimLeft, OutputVar, InputVar, Count',
  stringtrimright = 'StringTrimRight, OutputVar, InputVar, Count',
  stringupper = 'StringUpper, OutputVar, InputVar [, T]',
  suspend = 'Suspend [, Mode]',
  sysget = 'SysGet, OutputVar, Sub-command [, Param3]',
  thread = { 'Thread, Interrupt [, Duration, LineCount]',
             'Thread, NoTimers [, false]',
             'Thread, Priority, n', },
  tooltip = 'ToolTip [, Text, X, Y, WhichToolTip]',
  transform = 'Transform, OutputVar, Cmd, Value1 [, Value2]',
  traytip = 'TrayTip [, Title, Text, Seconds, Options]',
  urldownloadtofile = 'UrlDownloadToFile, URL, Filename',
  winactivate = 'WinActivate [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winactivatebottom = 'WinActivateBottom [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winclose = 'WinClose [, WinTitle, WinText, SecondsToWait, ExcludeTitle, ExcludeText]',
  winget = 'WinGet, OutputVar [, Cmd, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  wingetactivestats = 'WinGetActiveStats, Title, Width, Height, X, Y',
  wingetactivetitle = 'WinGetActiveTitle, OutputVar',
  wingetclass = 'WinGetClass, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  wingetpos = 'WinGetPos [, X, Y, Width, Height, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  wingettext = 'WinGetText, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  wingettitle = 'WinGetTitle, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winhide = 'WinHide [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winkill = 'WinKill [, WinTitle, WinText, SecondsToWait, ExcludeTitle, ExcludeText]',
  winmaximize = 'WinMaximize [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winmenuselectitem = 'WinMenuSelectItem, WinTitle, WinText, Menu [, SubMenu1, SubMenu2, SubMenu3, SubMenu4, SubMenu5, SubMenu6, ExcludeTitle, ExcludeText]',
  winminimize = 'WinMinimize [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winminimizeall = 'WinMinimizeAll',
  winminimizeallundo = 'WinMinimizeAllUndo',
  winmove = { 'WinMove, WinTitle, WinText, X, Y [, Width, Height, ExcludeTitle, ExcludeText]',
              'WinMove, X, Y', },
  WinRestore = 'WinRestore [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winset = 'WinSet, Attribute, Value [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winsettitle = { 'WinSetTitle, NewTitle',
                  'WinSetTitle, WinTitle, WinText, NewTitle [, ExcludeTitle, ExcludeText]', },
  winshow = 'WinShow [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
  winwait = 'WinWait [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]',
  winwaitactive = 'WinWaitActive [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]',
  winwaitclose = 'WinWaitClose [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]',
  winwaitnotactive = 'WinWaitNotActive [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]',
}

return docs
